# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:4

pipelines:
  default:
    - parallel:
        - step:
            name: "Cypress"
            script:
              - echo "Cypress tests if the application works correctly from the user's perspective"
              - /bin/bash cypress-test.sh
        - step:
            name: "Lint"
            script:
              - echo "Lint tests if the code meets the project's coding standards"
              - cd vue-app && npm install && npm run lint
        - step:
            name: "API Selenium-Test"
            script:
              - echo "API Selenium tests if the API returns the same data as Mock API"
              - cd selenium-tests && /bin/bash api-test.sh
        - step:
            name: "Security scan"
            script:
              - echo "Your security scan goes here..."

    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: "Deployment to Staging"
        deployment: staging
        script:
          - echo "Your deployment to staging script goes here..."
    - step:
        name: "Deployment to Production"
        deployment: production
        trigger: "manual"
        script:
          - echo "Your deployment to production script goes here..."
