version: "3.8"
services:
  vue:
    build:
      context: ./vue-app
      dockerfile: Dockerfile
      target: integration-stage
      args:
        VITE_API_BASE_URL: "${API_BASE_URL}"
    volumes:
      - ./vue-app/src:/app/src
      - shared-volume:/shared-volume
    env_file:
      - .env
    ports:
      - "${PORT_FRONTEND}:8080"
    user: "${UID}:${GID}"
  centos:
    depends_on:
      - vue
    build:
      context: ./centos
      dockerfile: Dockerfile
      args:
        UID: "${UID}"
        GID: "${GID}"
    ports:
      - "${PORT_FRONTEND_INTEGRATION}:3000"
    user: "${UID}:${GID}"
    volumes:
      - shared-volume:/shared-volume

volumes:
  shared-volume:
