name: tpms-frontend-development
services:
  vue:
    build:
      context: ../../vue-app
      dockerfile: Dockerfile
      target: development-stage
      args:
        VITE_API_BASE_URL: "${API_BASE_URL}"
        VITE_API_BASE_URL2: "${API_BASE_URL2}"
    volumes:
      - ../../vue-app/src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT_FRONTEND}:8080"
    depends_on:
      - nest
      - backend-middleware
  backend-middleware-mongodb:
    image: "mongo"
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
  backend-middleware:
    build:
      context: ../../backend-middleware
      dockerfile: Dockerfile
    volumes:
      - ../../backend-middleware/src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT_MIDDLEWARE}:8080"
    depends_on:
      - backend-middleware-mongodb
  nest:
    build:
      context: ../../nest-app
      dockerfile: Dockerfile
      target: development-stage
    volumes:
      - ../../nest-app/src:/app/src
    env_file:
      - .env
    ports:
      - "${PORT_BACKEND}:3001"
  npm:
    build: ../../tools/npm
    volumes:
      - ../../:/app
    profiles:
      - development
    user: "${UID}:${GID}"

volumes:
  mongodata:
